syntax = "LuaJIT"
indent_width = 2
column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
call_parentheses = "Always"
quote_style = "AutoPreferDouble"
alignment = "TrailingComments"
collapse_simple_statement = "Never"
space_after_function_names = "Never"

[sort_requires]
enabled = true
